name: Terraform

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      # ✅ ADD THIS (very important)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan

      - name: Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve